name: "Unit and style tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Unit & Style tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: imagick
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies with composer
        run: composer i --no-interaction --no-progress --no-suggest

      - name: Run php-code-sniffer
        run: composer check-style

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --testdox
